#ifndef WIDGET_DESC_H
#define WIDGET_DESC_H

typedef enum {
    DEFAULT_FORM_INDEX,
    SIM_SETTINGS_FORM_INDEX,
    OBJECT_COMMON_FORM_INDEX,
    MATERIAL_CONSTANTS_INDEX,
    PARTICLE_TYPE_SIZE_INDEX,
    PARTICLE_TYPE_SHAPE_INDEX,
    PARTICLE_TYPE_MATERIAL_INDEX,
    GEOMETRY_OBJECT_COMMON_FORM_INDEX,
    LINE_GEOMETRY_FORM_INDEX,
    RECTANGLE_GEOMETRY_FORM_INDEX,
    POINT_GEOMETRY_FORM_INDEX,
    PARTICLE_SOURCE_TYPE_FORM_INDEX,
    PARTICLE_SOURCE_INTENSITY_FORM_INDEX,
    REFLECTING_OBJECT_MATERIAL_FORM_INDEX,
    STOP_FORM_INDEX
} FormIndexEnum;

typedef struct
{
    FormIndexEnum FormIndex;
    const char *pszTextDesc;
    int ImageIndex;
} SFormDesc;

#endif // WIDGET_DESC_H
