//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NetObserver.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_NETOBSTYPE                  129
#define IDR_WORLD_PLANE_VIEW_TOOLBAR    129
#define IDR_NET_OBJECT_MENU             130
#define IDR_HOST_TRAFFIC_TOOLBAR        130
#define IDR_HOST_TRAFFIC                131
#define IDR_WORLD_TREE_VIEW_TOOLBAR     131
#define IDD_CONTROL_FORM                131
#define IDB_BITMAP_TREE                 132
#define IDR_HOST_CONFIG                 132
#define IDR_SUBNET_CONFIG               133
#define IDR_GROUP_EDITOR                134
#define IDD_DISPLAY_HOST_TRAFFIC_CTRLS  135
#define IDD_HOST_CONFIGURE_COMMON_PAGE  188
#define IDD_SUBNET_CONFIGURE_COMMON_PAGE 189
#define IDD_HOST_NAMES_CONTROL_FORM     190
#define IDD_SUBNET_NAMES_CONTROL_FORM   191
#define IDD_SUBNET_ADDRESS_CONTROL_FORM 192
#define IDD_HOST_ADDRESSES_CONTROL_FORM 193
#define IDD_HOST_PING_CONTROL_FORM      194
#define IDD_GROUP_EDITOR_FORM           195
#define IDD_NETWORK_FORM                196
#define IDD_PING_GROUP_EDITOR_FORM      197
#define IDD_APPEARANCE_GROUP_EDITOR_FORM 198
#define IDD_HOST_APPEARANCE_CONTROL_FORM 199
#define IDD_SUBNET_APPEARANCE_CONTROL_FORM 200
#define IDD_SNMP_GROUP_EDITOR_FORM      201
#define IDD_HOST_SNMP_CONTROL_FORM      202
#define IDC_GIVEN_NAME_EDIT             1000
#define IDC_BUTTON1                     1000
#define IDC_REFRESH_BUTTON              1000
#define IDC_NETBIOS_NAME_EDIT           1001
#define IDC_UNITS_STATIC                1001
#define IDC_NETBIOS_NAME_STATIC         1002
#define IDC_PACKETS_RADIO               1002
#define IDC_GIVEN_NAME_STATIC           1003
#define IDC_OCTETS_RADIO                1003
#define IDC_NETBIOS_DOMAIN_NAME_STATIC  1004
#define IDC_TCP_FROM_CHECK              1005
#define IDC_NETBIOS_DOMAIN_NAME_EDIT    1005
#define IDC_TCP_TO_CHECK                1006
#define IDC_NETBIOS_USER_NAME_STATIC    1006
#define IDC_UDP_FROM_CHECK              1007
#define IDC_NETBIOS_USER_NAME_EDIT      1007
#define IDC_UDP_TO_CHECK                1008
#define IDC_ICMP_FROM_CHECK             1009
#define IDC_ICMP_TO_CHECK               1010
#define IDC_IGMP_FROM_CHECK             1011
#define IDC_IGMP_TO_CHECK               1012
#define IDC_TOTAL_FROM_CHECK            1013
#define IDC_TOTAL_TO_CHECK              1014
#define IDC_TIME_RANGE_STATIC           1015
#define IDC_TIME_FROM_STATIC            1016
#define IDC_FROM_TIME_EDIT              1017
#define IDC_TIME_TO_STATIC              1018
#define IDC_APPLY_BUTTON                1018
#define IDC_TO_TIME_EDIT                1019
#define IDC_CANCEL_BUTTON               1019
#define IDC_IPADDRESS_STATIC            1019
#define IDC_IPADDRESS_EDIT              1020
#define IDC_SUBNET_MASK_STATIC          1021
#define IDC_GROUP_STATIC                1021
#define IDC_SUBNET_MASK_EDIT            1022
#define IDC_GROUP_COMBO                 1022
#define IDC_MACADDRESS_STATIC           1023
#define IDC_MACADDRESS_EDIT             1024
#define IDC_GROUP_NAME_EDIT             1024
#define IDC_KEEPALIVE_STATIC            1027
#define IDC_ENABLED_CHECK               1028
#define IDC_PERIOD_EDIT                 1029
#define IDC_SECONDS_STATIC              1030
#define IDC_GROUP_PARAMS_EDIT           1031
#define IDC_STATE_STATIC                1032
#define IDC_KEEPALIVE_STATUS_EDIT       1037
#define IDC_HOSTS_LIST                  1038
#define IDC_COLORS_PANEL                1039
#define IDC_ORDINARY_COLOR_STATIC       1040
#define IDC_WARNING_COLOR_STATIC        1041
#define IDC_ALARM_COLOR_STATIC          1042
#define IDC_TEXT_COLOR_STATIC           1043
#define IDC_INSTANCE_STATIC             1120
#define IDC_ORDINARY_COLOR_BUTTON       1201
#define IDC_WARNING_COLOR_BUTTON        1202
#define IDC_ALARM_COLOR_BUTTON          1203
#define IDC_TEXT_COLOR_BUTTON           1204
#define IDC_COMMUNITY_NAME_STATIC       1301
#define IDC_COMMUNITY_NAME_EDIT         1302
#define IDC_PASSWORD_STATIC             1303
#define IDC_PASSWORD_EDIT               1304
#define IDC_RETRIES_STATIC              1305
#define IDC_RETRIES_EDIT                1306
#define IDC_RETRIES_SPIN                1307
#define ID_A_B                          32771
#define ID_BUTTON32772                  32772
#define ID_HOST_DELETE                  32773
#define ID_HOST_CONFIGURE               32774
#define ID_VIEW_INITIALVIEW             32775
#define ID_BUTTON32775                  32776
#define ID_BUTTON32776                  32777
#define ID_BUTTON32777                  32778
#define ID_VIEW_ZOOM_IN_TRAFFIC         32779
#define ID_BUTTON32778                  32780
#define ID_VIEW_ZOOM_IN                 32781
#define ID_VIEW_ZOOM_RECTANGLE          32782
#define ID_VIEW_DRAG_SCROLL             32783
#define ID_BUTTON32781                  32784
#define ID_VIEW_ZOOM_OUT                32785
#define ID_BUTTON32782                  32786
#define ID_VIEW_ZOOM_OUT_TRAFFIC        32787
#define ID_BUTTON32787                  32787
#define ID_VIEW_SELECT                  32788
#define ID_HOST_HIDE                    32789
#define ID_SUBNET_CONFIGURE             32790
#define ID_TREE_VIEW_DRAG_SCROLL        32791
#define ID_SUBNET_DELETE                32792
#define ID_TREE_VIEW_SELECT             32793
#define ID_HOST_LOOK_TRAFFIC            32794
#define ID_BUTTON32795                  32795
#define ID_TREE_VIEW_INITIALVIEW        32796
#define ID_BUTTON32796                  32797
#define ID_BUTTON32799                  32798
#define ID_VIEW_SHOW_IGNORED_OBJECTS    32799
#define ID_VIEW_SHOW_HIDDEN_OBJECTS     32800
#define ID_BUTTON32820                  32820
#define ID_TOOLS_GROUP_EDITOR           32820
#define ID_VIEW_SORTITEMS_BYNAME        32821
#define ID_VIEW_SORTITEMS_BYIPADDRESS   32822
#define ID_EDIT_DELETE_GROUP            32824
#define ID_EDIT_CREATE_PINGGROUP        32825
#define ID_EDIT_CREATE_SNMPGROUP        32826
#define ID_EDIT_CREATE_APPEARANCEGROUP  32827
#define ID_INDICATOR_OBJECT             61446
#define ID_INDICATOR_DATETIME           61447
#define ID_INDICATOR_TRAFFIC            61449

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1308
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
