version: '2'
services:
  rest-proxy:
    image: confluentinc/cp-kafka-rest:4.1.2
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: ${OOMA_HOSTNAME}
      KAFKA_REST_BOOTSTRAP_SERVERS: 'kafkalte1:9092,kafkalte2:9092,kafkalte3:9092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
    restart: always
